### PR TITLE
Save variable values in state for uses-credentials directive

### LINKED ISSUE #341: `@uses-credentials` Directive does not resolve variables
**Describe the bug**
Gyro errors on state resolve when using a variable as the value to the @uses-credentials directive.

**To Reproduce**
Create a simple VPC using a variable with the @uses-credentials directive:
```
region: 'us-east-1'

# VPC
aws::vpc "$(region)-vpc"
    cidr-block: "10.0.0.0/16"
    @uses-credentials: $region
```

Gyro up:
```
gyro up test.gyro
⟳ Refreshed resources: 99

Looking for changes...

+ Create aws::vpc us-east-1-vpc

Are you sure you want to change resources? (y/N) y

+ Creating aws::vpc us-east-1-vpc OK
```

Gyro up again:
```
gyro up test.gyro

Error: Can't create aws::vpc us-east-1-vpc resource!

Caused by: Error: Can't resolve region!

In test.gyro on line 5 from column 24 to 34:
5:     @uses-credentials: $('region')
6:     'cidr-block': '10.0.0.0/16'
```

**Expected behavior**
Gyro should be able to resolve the variable, or save the value of the variable in the state.

### PR DESCRIPTION
**Pull request by harjain99**
Fixes #341

### CODE REVIEW

File: core/src/main/java/gyro/core/auth/UsesCredentialsDirectiveProcessor.java [hunk 1]
```diff
@@ -29,17 +33,31 @@
...
+            if (diffableScope.getStateNodes().stream().filter(o -> o instanceof DirectiveNode).noneMatch(o -> {
+                DirectiveNode directiveNode = (DirectiveNode) o;
+                String directiveNodeArgument = (String) root.convertValue(
+                    String.class, root.getEvaluator().visit(directiveNode.getArguments().get(0), scope));
+                String stateNodeArgument = (String) root.convertValue(
+                    String.class, root.getEvaluator().visit(stateNode.getArguments().get(0), scope));
+                return directiveNode.getName().equals(stateNode.getName()) && directiveNodeArgument.equals(
+                    stateNodeArgument);
+            })) {
+                diffableScope.getStateNodes().add(stateNode);
```
Comment (deepanjan90) [inline core/src/main/java/gyro/core/auth/UsesCredentialsDirectiveProcessor.java:57]: As there can only be one uses-credentials inside a block, only checking if it is present is fine I guess.

There can be a case where the variable that uses-credentials uses is changed, we still would want the state to have the old value rather than another new `@uses-credentials` entry. 

The following handles that as well.

```suggestion

            DirectiveNode stateNode = new DirectiveNode(
                node.getName(),
                Collections.singletonList(new ValueNode(argument)),
                node.getOptions(),
                node.getBody(),
                node.getSections());

            if (diffableScope.getStateNodes().stream()
                .filter(o -> o instanceof DirectiveNode)
                .map(o -> ((DirectiveNode) o))
                .noneMatch(o -> o.getName().equals(node.getName()))) {
                diffableScope.getStateNodes().add(stateNode);
```

**Review by deepanjan90 — APPROVED** [review]

**Review by beetlebugorg — APPROVED** [review]
