### PR TITLE
Fix Resource fails to delete if created using @uses-credentials

### LINKED ISSUE #250: Resource fails to delete if created using @uses-credentials
**Describe the bug**
If a resource is created using the `@uses-credentials` directive to use an alternate credential, deleting the resource fails.

**To Reproduce**

init file
```
.
.
#default credentials
@credentials '<type>'
    .
    .
@end

#alternate credentials
@credentials '<type>' 'alternate-credentials'
    .
    .
    .
@end

```

resource config file
```
aws::vpc vpc-example
     cidr-block: "10.0.0.0/16"
     @uses-credentials: "alternate-credentials"
end
```

**Expected behavior**
Resource should be successfully be deleted

**Stacktrace**
```
Looking for changes...

- Delete aws::vpc vpc-example (vpc-07487b85e4b00dc47)


Are you sure you want to change resources? (y/N) y

- Deleting aws::vpc vpc-example (vpc-07487b85e4b00dc47)
Error: Can't delete aws::vpc vpc-example resource!

Caused by: Unexpected error: software.amazon.awssdk.services.ec2.model.Ec2Exception: The vpc ID 'vpc-07487b85e4b00dc47' does not exist (Service: Ec2, Status Code: 400, Request ID: 546cea1e-adf1-42ea-8b83-7e514c660a24)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:81)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:61)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:114)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:87)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:122)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:148)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:102)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.ec2.DefaultEc2Client.deleteVpc(DefaultEc2Client.java:6873)
	at gyro.aws.ec2.VpcResource.delete(VpcResource.java:376)
	at gyro.core.diff.Delete.execute(Delete.java:60)
	at gyro.core.diff.Diff.executeChange(Diff.java:412)
	at gyro.core.diff.Diff.executeDelete(Diff.java:384)
	at gyro.core.diff.Diff.execute(Diff.java:348)
	at gyro.core.command.UpCommand.doExecute(UpCommand.java:63)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:131)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:75)
	at gyro.cli.Gyro.run(Gyro.java:198)
	at gyro.cli.Gyro.main(Gyro.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Additional context**
When deleting the resource, it looses the value for using alternate credentials and instead uses the default credentials which leads to this failure

### PR DESCRIPTION
**Pull request by deepanjan90**
Fixes #250 

When the current and pending is evaluated using the diff, current looses all directive level details

 - Add the directive level detail back to the resources belonging to current
 - Process the credential directive again to add back the credential for deleting

### CODE REVIEW

File: core/src/main/java/gyro/core/command/AbstractConfigCommand.java [hunk 1]
```diff
@@ -196,11 +198,23 @@ private void refreshResources(RootScope scope) {
             String name = DiffableInternals.getName(resource);
 
             try {
+                Node credentialNode = DiffableInternals.getScope(resource)
```
Comment (beetlebugorg) [inline core/src/main/java/gyro/core/command/AbstractConfigCommand.java]: I'd look into implementing this as a ChangeProcessor. Similar to `ConfiguredFieldsChangeProcessor`.

File: core/src/main/java/gyro/core/diff/Diff.java [hunk 2]
```diff
@@ -279,6 +285,21 @@ private Change newDelete(Diffable diffable) {
         return delete;
     }
 
+    private void setCredentials(Diffable diffable) {
```
Comment (beetlebugorg) [inline core/src/main/java/gyro/core/diff/Diff.java]: This name should be more descriptive, `setCredentials` implies a normal setter but this appears to be searching around in state for the appropriate credentials to use to delete.

File: core/src/main/java/gyro/core/diff/Diff.java [hunk 3]
```diff
@@ -279,6 +285,21 @@ private Change newDelete(Diffable diffable) {
         return delete;
     }
 
+    private void setUsesCredentialFromState(Diffable diffable) {
+        DiffableScope scope = DiffableInternals.getScope(diffable);
+
+        Node node = scope.getStateNodes()
+            .stream()
+            .filter(o -> o instanceof DirectiveNode)
+            .filter(o -> ((DirectiveNode) o).getName().equals("uses-credentials"))
```
Comment (beetlebugorg) [inline core/src/main/java/gyro/core/diff/Diff.java]: This should be generic rather that directly mention a specific uses-credentials.
